function cmPoints = cmPointsFunc(in1)
%CMPOINTSFUNC
%    CMPOINTS = CMPOINTSFUNC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    18-Dec-2021 16:48:30

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
q5 = in1(5,:);
cmPoints = reshape([cos(q1+q3+q5+pi./2.0).*(-4.0./2.5e+1),cos(q1+q5+pi./2.0).*(-2.9e+1./1.0e+2)-cos(q1+q3+q5+pi./2.0).*(2.0./5.0),cos(q1+q5+pi./2.0).*(-2.0./5.0)-cos(q1+q3+q5+pi./2.0).*(2.0./5.0)+cos(q5+pi./2.0).*(6.0./2.5e+1),cos(q1+q5+pi./2.0).*(-2.0./5.0)+cos(q2+q5+pi./2.0).*(1.1e+1./1.0e+2)-cos(q1+q3+q5+pi./2.0).*(2.0./5.0),cos(q1+q5+pi./2.0).*(-2.0./5.0)+cos(q2+q5+pi./2.0).*(2.0./5.0)-cos(q1+q3+q5+pi./2.0).*(2.0./5.0)+cos(q2+q4+q5+pi./2.0).*(6.0./2.5e+1),sin(q1+q3+q5+pi./2.0).*(-4.0./2.5e+1),sin(q1+q5+pi./2.0).*(-2.9e+1./1.0e+2)-sin(q1+q3+q5+pi./2.0).*(2.0./5.0),sin(q1+q5+pi./2.0).*(-2.0./5.0)-sin(q1+q3+q5+pi./2.0).*(2.0./5.0)+sin(q5+pi./2.0).*(6.0./2.5e+1),sin(q1+q5+pi./2.0).*(-2.0./5.0)+sin(q2+q5+pi./2.0).*(1.1e+1./1.0e+2)-sin(q1+q3+q5+pi./2.0).*(2.0./5.0),sin(q1+q5+pi./2.0).*(-2.0./5.0)+sin(q2+q5+pi./2.0).*(2.0./5.0)-sin(q1+q3+q5+pi./2.0).*(2.0./5.0)+sin(q2+q4+q5+pi./2.0).*(6.0./2.5e+1)],[5,2]);
