function Ge = GeFunc(in1)
%GEFUNC
%    GE = GEFUNC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    18-Dec-2021 16:49:21

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
q5 = in1(5,:);
Ge = [sin(q1+q3+q5).*1.1803392e+2+sin(q1+q5).*1.0567332e+2;sin(q2+q4+q5).*(-7.53408)-sin(q2+q5).*1.989468e+1;sin(q1+q3+q5).*1.1803392e+2;sin(q2+q4+q5).*(-7.53408);sin(q1+q3+q5).*1.1803392e+2-sin(q2+q4+q5).*7.53408+sin(q1+q5).*1.0567332e+2-sin(q2+q5).*1.989468e+1-sin(q5).*2.82528e+1;0.0;3.1392e+2];
