function jointPoints = jointPointsFunc(in1)
%JOINTPOINTSFUNC
%    JOINTPOINTS = JOINTPOINTSFUNC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    18-Dec-2021 16:48:29

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
q5 = in1(5,:);
jointPoints = reshape([0.0,cos(q1+q3+q5+pi./2.0).*(-2.0./5.0),cos(q1+q5+pi./2.0).*(-2.0./5.0)-cos(q1+q3+q5+pi./2.0).*(2.0./5.0),cos(q1+q5+pi./2.0).*(-2.0./5.0)-cos(q1+q3+q5+pi./2.0).*(2.0./5.0)+cos(q5+pi./2.0).*(6.3e+1./1.0e+2),cos(q1+q5+pi./2.0).*(-2.0./5.0)-cos(q1+q3+q5+pi./2.0).*(2.0./5.0),cos(q1+q5+pi./2.0).*(-2.0./5.0)+cos(q2+q5+pi./2.0).*(2.0./5.0)-cos(q1+q3+q5+pi./2.0).*(2.0./5.0),cos(q1+q5+pi./2.0).*(-2.0./5.0)+cos(q2+q5+pi./2.0).*(2.0./5.0)-cos(q1+q3+q5+pi./2.0).*(2.0./5.0)+cos(q2+q4+q5+pi./2.0).*(2.0./5.0),0.0,sin(q1+q3+q5+pi./2.0).*(-2.0./5.0),sin(q1+q5+pi./2.0).*(-2.0./5.0)-sin(q1+q3+q5+pi./2.0).*(2.0./5.0),sin(q1+q5+pi./2.0).*(-2.0./5.0)-sin(q1+q3+q5+pi./2.0).*(2.0./5.0)+sin(q5+pi./2.0).*(6.3e+1./1.0e+2),sin(q1+q5+pi./2.0).*(-2.0./5.0)-sin(q1+q3+q5+pi./2.0).*(2.0./5.0),sin(q1+q5+pi./2.0).*(-2.0./5.0)+sin(q2+q5+pi./2.0).*(2.0./5.0)-sin(q1+q3+q5+pi./2.0).*(2.0./5.0),sin(q1+q5+pi./2.0).*(-2.0./5.0)+sin(q2+q5+pi./2.0).*(2.0./5.0)-sin(q1+q3+q5+pi./2.0).*(2.0./5.0)+sin(q2+q4+q5+pi./2.0).*(2.0./5.0)],[7,2]);
